### ISSUE TITLE
Unable to subscribe to dcrainmaker.com RSS feed

### ISSUE THREAD

**Issue by rex4539** [brentsimmons/Evergreen#144]
NetNewsWire for example subscribes just fine.

**Comment by danielpunkass** [comment]
I took a look at this. There are a couple problems exhibited here: 

1. The title for the feed is not deduced from the home page, so it adds as "Untitled".
2. The feed, once added, does not yield any articles when refreshing.

The refresh issue is caused because the content of this feed triggers NSData+RSParser's "bytesAreProbablyHTML". The content of this feed includes <meta> tags which are among the tags that RSParser infers HTML from.

Probably FeedType.swift should check for "probably" RSS and Atom before checking for HTML.
