### ISSUE TITLE
Duplicate articles

### ISSUE THREAD

**Issue by rex4539** [brentsimmons/Evergreen#324]
git @ 9fce370

I still get duplicate articles.

![screen shot 2018-02-03 at 20 04 56](https://user-images.githubusercontent.com/227442/35770089-def51920-091d-11e8-9d59-a284df058839.png)

**Comment by brentsimmons** [comment]
What’s the URL of the feed?

**Comment by rex4539** [comment]
http://developer.apple.com/news/rss/news.rss

**Comment by brentsimmons** [comment]
Here’s what I think happened:

The feed URL is now being redirected to the https version of that URL.

Inside the feed, the guids are different: they’re https URLs instead of http URLs.

Evergreen matches articles based on guids. A new guid means a new article.

Evergreen could try to interpret the guid and correct for things like this — but there is so much peril there that it’s not worth it.

Instead, we live this with this fact of life with RSS readers: sometimes something in a feed changes that causes reruns. (This should definitely go in the FAQ.)
